# Generated by Django 4.2.5 on 2023-10-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipeingredients_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredients',
            name='quantity_as_float',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
